include:
  - board: xiao_ble
    shield: totem_left
    snippet: zmk-usb-logging
  - board: xiao_ble
    shield: totem_right
    snippet: zmk-usb-logging
  - board: xiao_ble
    shield: settings_reset
